module.exports.descriptors = [
    'Pho Mot',
    'Pho Hai',
    'Pho Ba',
    'Pho Bon',
    'Pho Nam',
    'Pho Sau',
    'Pho Bay',
    'Pho Tam',
    'Pho Chin',
    'Pho Muoi',
    'Pho Yi',
    'Pho Be',
    'Pho Ce',
    'Pho Nhe',
    'Pho He',
    'Pho Xe',
    'Pho Bo',
    'Pho Cha',
    'Pho Lon',
];

module.exports.places = [
    'Hanoi',
    'Ho Chi Minh City',
    'Da Nang',
    'Hue',
    'Nha Trang',
    'Can Tho',
    'Ha Long',
    'Vung Tau',
    'Phan Thiet',
    'Hoi An',
    'Phu Quoc',
    'Bien Hoa',
    'Rach Gia',
    'Quy Nhon',
    'Tam Ky',
    'Long Xuyen',
    'Thu Dau Mot',
    'Buon Ma Thuot',
    'Da Lat',
    'My Tho',
    'Nam Dinh',
    'Thai Nguyen',
];

